# Generated by Django 4.0.2 on 2022-02-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://wallpaperscraft.com/download/car_bolide_racing_252459/1280x960', upload_to='profile_pics'),
        ),
    ]
